AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation sample template LAMP_Single_Instance: Create a LAMP stack
  using a single EC2 instance and a local MySQL database for storage. This
  template demonstrates using the AWS CloudFormation bootstrap scripts to
  install the packages and files necessary to deploy the Apache web server, PHP,
  and MySQL at instance launch time. **WARNING** This template creates an Amazon
  EC2 instance. You will be billed for the AWS resources used if you create a
  stack from this template.
Parameters:
  KeyName:
    Description: Key pair name
    Type: 'AWS::EC2::KeyPair::KeyName'
Resources:
  WebServer:
    Type: 'AWS::EC2::Instance'
    Metadata:
      Comment1: Configure bootstrap helpers to install python
      'AWS::CloudFormation::Init':
        configSets:
          Install:
            - Install
      Files:
          /home/ubuntu/hello.txt:
              content: "Hello, there!"
    Properties:
      AvailabilityZone: us-west-2c
      ImageId: ami-06e54d05255faf8f6
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - ec2-test
      Tags:
        - Key: Name
          Value: Test-ec2
Outputs:
  WebsiteURL:
    Description: URL for LAMP stack
    Value: !GetAtt 
      - WebServer
      - PublicDnsName
